# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: ggproxy
before:
  hooks:
    - go mod tidy
builds:
  - id: ggproxy
    main: ./cmd/ggproxy
    binary: usr/local/bin/ggproxy
    gobinary: garble
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - "amd64"
      - "arm"
      - "arm64"
archives:
  - id: ggproxy
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      "386": "i386"
checksum:
  name_template: "{{ .ProjectName }}-{{ .Tag }}-checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
release:
  draft: false
  replace_existing_draft: true
  prerelease: "true" # Don't remove the quotes, it's supposed to be a string, not a boolean.
  mode: append
  header: |
    **[CHANGELOG.md](https://github.com/graph-guard/ggproxy/blob/ci/CHANGELOG.md#{{ .Env.COMPACT_TAG }})**
changelog:
  skip: true
