# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: ggproxy
before:
  hooks:
    - go mod tidy
builds:
  - id: ggproxy
    main: ./cmd/ggproxy
    binary: usr/local/bin/ggproxy
    gobinary: garble
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X 'github.com/graph-guard/ggproxy/lvs.PublicKey={{ .Env.PUB_KEY }}'
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
archives:
  - id: ggproxy
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      386: i386
    files:
      - src: etc/
        info:
          owner: root
          group: ggproxy
          mode: 0664
checksum:
  name_template: "{{ .ProjectName }}-{{ .Tag }}-checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
release:
  draft: true
  replace_existing_draft: true
  prerelease: true
  mode: append
  header: |
    ## GG {{ .Date }}

    **[CHANGELOG.md](https://github.com/graph-guard/ggproxy/blob/{{ .Tag }}/CHANGELOG.md)**
changelog:
  skip: true
