# /etc/ggproxy/config.yaml

proxy:
  # Address and port of the proxy server.
  host: localhost:8000
  # Optional, enables HTTPS.
  #tls:
    # Certificate file path.
    #cert-file: proxy.cert
    # Private key file path.
    #key-file: proxy.key
  # Optional, in bytes, default: 4MiB.
  #max-request-body-size: 1024

# Optional, enables API server.
api:
  # Address and port of the API server.
  host: localhost:3000
  # Optional, enables HTTPS.
  #tls:
    # Certificate file path.
    #cert-file: api.cert
    # Private key file path.
    #key-file: api.key
