# /etc/ggproxy/services_enabled/example_service/config.yaml

# The service's display name
name: "Example Service"

# Destination URL (where to proxy requests to)
forward_url: "http://localhost:8080/path"

# false for forwarding the original request,
# true for the reduced version.
forward_reduced: true
