// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type ServiceStatistics struct {
	BlockedRequests     int `json:"blockedRequests"`
	ForwardedRequests   int `json:"forwardedRequests"`
	ReceivedBytes       int `json:"receivedBytes"`
	SentBytes           int `json:"sentBytes"`
	HighestResponseTime int `json:"highestResponseTime"`
	AverageResponseTime int `json:"averageResponseTime"`
}

type TemplateStatistics struct {
	Matches             int       `json:"matches"`
	LastMatch           time.Time `json:"lastMatch"`
	HighestResponseTime int       `json:"highestResponseTime"`
	AverageResponseTime int       `json:"averageResponseTime"`
}
