// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type MatchResult struct {
	Template       *Template `json:"template"`
	Forwarded      *string   `json:"forwarded"`
	TimeParsingNs  float64   `json:"timeParsingNS"`
	TimeMatchingNs float64   `json:"timeMatchingNS"`
}

type ServiceStatistics struct {
	BlockedRequests       int `json:"blockedRequests"`
	ForwardedRequests     int `json:"forwardedRequests"`
	ReceivedBytes         int `json:"receivedBytes"`
	SentBytes             int `json:"sentBytes"`
	HighestProcessingTime int `json:"highestProcessingTime"`
	AverageProcessingTime int `json:"averageProcessingTime"`
	HighestResponseTime   int `json:"highestResponseTime"`
	AverageResponseTime   int `json:"averageResponseTime"`
}

type TemplateStatistics struct {
	Matches               int       `json:"matches"`
	LastMatch             time.Time `json:"lastMatch"`
	HighestProcessingTime int       `json:"highestProcessingTime"`
	AverageProcessingTime int       `json:"averageProcessingTime"`
	HighestResponseTime   int       `json:"highestResponseTime"`
	AverageResponseTime   int       `json:"averageResponseTime"`
}
