query X {
	a {
		a0 {
			a00(
				a00_0: {
					a00_00: {
						a00_000: -273
					}
					a00_01: {
						a00_010: "eagle"
                        a00_011: "hawk"
                        a00_012: "falcon"
					}
					a00_02: {
						a00_020: [ "eagle", "hawk", "falcon" ]
                        a00_031: [ -273, -273, -273 ]
					}
					a00_03: {
						a00_030: [
                            {
                                a00_030x0: [0, 1]
                                a00_030x1: "x"
                            },
                            {
                                a00_030x0: [1, 0]
                                a00_030x1: "y"
                            }
                        ]
					}
                }
				a00_1: {
                    a00_10: {
                        a00_100: {
                            a00_1000: {
                                a00_10000: [ -13, -88 ]
                                a00_10001: "deep"
                                a00_10002: "not shallow"
                            }
                        }
                        a00_101: {
                            a00_1010: "hohoho"
                            a00_1011: -1
                        }
                    }
                }
			) {
                a000(
                    a000_0: {
                        a000_00: {
                            a000_000: "coffe?"
                            a000_001: [ "yes", "please" ]
                        }
                    }
                    a000_1: {
                        a000_10: 0
                    }
                ) {
                    a0000(
                        a0000_0: {
                            a0000_00: 65535
                            a0000_01: {
                                a0000_010: [
                                    {
                                        a0000_01000: "I need your clothes, boots and motorcycle"
                                    }
                                ]
                            }
                        }
                    )
                    a0001 {
                        a00000(
                            a00000_0: {
                                a00000_00: {
                                    a00000_000: {
                                        a00000_0000: "Not enought wood"
                                        a00000_0001: "Milord"
                                    }
                                }
                            }
                        )
                    }
                }
                a001(
                    a001_0: "surprise!"
                    a001_1: {
                        a001_10: {
                            a001_100: {
                                a001_1001: true
                                a001_1002: [false, true]
                            }
                            a001_101: {
                                a001_1010: {
                                    a001_10100: "enough"
                                }
                            }
                        }
                    }
                )
            }
		}
        a1 {
            a10 {
                a100(
                    a100_0: {
                        a100_00: [0, 1, 2, 3]
                    }
                )
                a101(
                    a101_0: {
                        a101_00: {
                            a101_000: "putin huilo"
                        }
                    }
                )
            }
        }
	}
}
