on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main
      - ci

name: CI
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.*
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run linting
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.4
      - name: Run go vet
        continue-on-error: true
        run: go vet ./...
      - name: Test with coverage
        run: |
          go test -v -race -covermode=count -coverprofile=coverage.out
      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.0.9
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.3
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
