on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main
      - ci

env:
  SERVICE_USER: KernelPryanic

name: CI
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.*
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Tidy dependencies
        run: |
          git config --global url."https://${SERVICE_USER}:${{secrets.CI}}@github.com".insteadOf "https://github.com"
          go env -w GOPRIVATE=github.com/graph-guard/*
          go mod tidy
      - name: Run linting
        uses: golangci/golangci-lint-action@v3
        with:
          args: --out-${NO_FUTURE}format colored-line-number
          version: v1.49
      - name: Run go vet
        continue-on-error: true
        run: go vet ./...
      - name: Test with coverage
        run: |
          go test -v -race -covermode=count -coverprofile=coverage.out
      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.0.9
      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
