name: CI/CD
on:
  push:
    branches:
      - main
      - ci
    tags:
      - "^[0-9]+.[0-9]+.[0-9]+$"
  pull_request:
    branches:
      - main
      - ci

env:
  SERVICE_USER: KernelPryanic

jobs:
  init:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.*
      - name: Tidy dependencies
        run: |
          git config --global url."https://${SERVICE_USER}:${{secrets.CI}}@github.com".insteadOf "https://github.com"
          go env -w GOPRIVATE=github.com/graph-guard/*
          go mod tidy
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

  lint:
    runs-on: ubuntu-22.04
    needs:
      - init
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.*
      - name: Use cached dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
      - name: Run linting
        uses: golangci/golangci-lint-action@v3
        with:
          args: --out-${NO_FUTURE}format colored-line-number
          version: v1.49

  test:
    runs-on: ubuntu-22.04
    needs:
      - init
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.*
      - name: Use cached dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
      - name: Run go vet
        continue-on-error: true
        run: go vet ./...
      - name: Run tests
        run: |
          go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
      # - name: Convert coverage.out to coverage.lcov
      #   uses: jandelgado/gcov2lcov-action@v1.0.9
      # - name: Coveralls
      #   uses: coverallsapp/github-action@1.1.3
      #   with:
      #     github-token: ${{ secrets.CI }}
      #     path-to-lcov: coverage.lcov

  build:
    runs-on: ubuntu-22.04
    needs:
      - lint
      - test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.*
      - name: Use cached dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
      - name: Install build dependencies
        run: |
          go install github.com/goreleaser/goreleaser@v1.11.2
          go install mvdan.cc/garble@v0.7.1
