name: CI/CD
on:
  push:
    branches:
      - main
      - ci
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - main
      - ci

env:
  GITHUB_USER: KernelPryanic

jobs:
  init:
    runs-on: ubuntu-22.04
    steps:
      - name: Init
        uses: graph-guard/ggproxy@ci
      - name: Tidy dependencies
        run: |
          git config --global url."https://${GITHUB_USER}:${{secrets.GITHUB_TOKEN}}@github.com".insteadOf "https://github.com"
          go env -w GOPRIVATE=github.com/graph-guard/*
          go mod tidy

  lint:
    runs-on: ubuntu-22.04
    needs:
      - init
    steps:
      - name: Init
        uses: graph-guard/ggproxy@ci
      - name: Run linting
        uses: golangci/golangci-lint-action@v3
        with:
          args: --out-${NO_FUTURE}format colored-line-number
          version: v1.49

  test:
    runs-on: ubuntu-22.04
    needs:
      - init
    steps:
      - name: Init
        uses: graph-guard/ggproxy@ci
      - name: Run go vet
        continue-on-error: true
        run: go vet ./...
      - name: Run tests
        run: |
          go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
      # - name: Convert coverage.out to coverage.lcov
      #   uses: jandelgado/gcov2lcov-action@v1.0.9
      # - name: Coveralls
      #   uses: coverallsapp/github-action@1.1.3
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     path-to-lcov: coverage.lcov

  release:
    runs-on: ubuntu-22.04
    needs:
      - lint
      - test
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Init
        uses: graph-guard/ggproxy@ci
        with:
          fetch-depth: 0
      - name: Install build dependencies
        run: |
          go install mvdan.cc/garble@v0.7.1
          go install github.com/git-chglog/git-chglog/cmd/git-chglog@v0.15.1
      - name: Generate changelog
        run: git-chglog -o CHANGELOG.md
      - name: Commit changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Changelog update
          file_pattern: CHANGELOG.md
      - name: Release
        uses: goreleaser/goreleaser-action@v3
        with:
          version: ~> 1.11
          args: --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUB_KEY: ${ secrets.PUB_KEY }
