name: CI/CD
on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    types:
      - opened
    branches:
      - main

env:
  SERVICE_USER: KernelPryanic

jobs:
  init:
    runs-on: ubuntu-22.04
    steps:
      - name: Init
        uses: graph-guard/ggproxy@ci
      - name: Tidy dependencies
        run: |
          git config --global url."https://${SERVICE_USER}:${{secrets.SERVICE_TOKEN}}@github.com".insteadOf "https://github.com"
          go env -w GOPRIVATE=github.com/graph-guard/*
          go mod tidy

  lint:
    runs-on: ubuntu-22.04
    needs:
      - init
    steps:
      - name: Init
        uses: graph-guard/ggproxy@ci
      - name: Run linting
        uses: golangci/golangci-lint-action@v3
        with:
          args: --out-${NO_FUTURE}format colored-line-number
          version: v1.49

  test:
    runs-on: ubuntu-22.04
    needs:
      - init
    steps:
      - name: Init
        uses: graph-guard/ggproxy@ci
      - name: Run go vet
        continue-on-error: true
        run: go vet ./...
      - name: Run tests
        run: |
          go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
      # - name: Convert coverage.out to coverage.lcov
      #   uses: jandelgado/gcov2lcov-action@v1.0.9
      # - name: Coveralls
      #   uses: coverallsapp/github-action@1.1.3
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     path-to-lcov: coverage.lcov

  changelog:
    runs-on: ubuntu-22.04
    needs:
      - lint
      - test
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Init
        uses: graph-guard/ggproxy@ci
        with:
          fetch-depth: 0
      - name: Install git-chglog
        run: go install github.com/git-chglog/git-chglog/cmd/git-chglog@v0.15.1
      - name: Generate changelog
        run: git-chglog -o CHANGELOG.md
      - name: Stash changelog
        run: git stash push CHANGELOG.md
      - name: Get branch of the tag
        run: |
          branch=$(git branch -r --contains $GITHUB_REF | cut -c 3-)
          echo "TAG_BRANCH=${branch/origin\/}" >> $GITHUB_ENV
      - name: Checkout to the tag branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TAG_BRANCH }}
      - name: Apply changelog
        run: git stash apply
      - name: Commit changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(changelog): Update changelog"
          file_pattern: CHANGELOG.md

  release:
    runs-on: ubuntu-22.04
    needs:
      - lint
      - test
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Init
        uses: graph-guard/ggproxy@ci
        with:
          fetch-depth: 0
      - name: Install build dependencies
        run: |
          go install mvdan.cc/garble@v0.7.1
      - name: Generate compact tag
        run: echo "COMPACT_TAG=${GITHUB_REF_NAME//./}" >> $GITHUB_ENV
      - name: Release
        uses: goreleaser/goreleaser-action@v3
        with:
          version: ~> 1.11
          args: --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUB_KEY: ${{ secrets.PUB_KEY }}
          COMPACT_TAG: ${{ env.COMPACT_TAG }}
