name: Init
on:
  push:
    branches:
      - main
      - ci
    tags:
      - "^[0-9]+.[0-9]+.[0-9]+$"
  pull_request:
    branches:
      - main
      - ci

env:
  SERVICE_USER: KernelPryanic

jobs:
  init:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.*
      - name: Tidy dependencies
        run: |
          git config --global url."https://${SERVICE_USER}:${{secrets.CI}}@github.com".insteadOf "https://github.com"
          go env -w GOPRIVATE=github.com/graph-guard/*
          go mod tidy
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ${GOPATH}/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
